import {
  burger1,
  burger2,
  burger3,
  burger4,
  burger5,
  burger6,
  burgerBaconEgg,
  burgerVegan,
  drink1,
  drink2,
  drink3,
  frite1,
  frite2,
  frite3,
  iceCream,
  wedges1,
  wedges2,
} from "../assets/index"

export const fakeMenu1 = [
  {
    id: 1,
    imageSource: burger1,
    title: "Burger 1",
    price: 5.297,
    quantity: 0,
    isAvailable: true,
    isAdvertised: false,
  },
  {
    id: 2,
    imageSource: burger2,
    title: "Burger 2",
    price: 7.556,
    quantity: 0,
    isAvailable: true,
    isAdvertised: false,
  },
]

export const fakeMenu2 = [
  {
    id: 1,
    imageSource: burgerBaconEgg,
    title: "Burger Smoke BBQ",
    price: 5.598,
    quantity: 0,
    isAvailable: true,
    isAdvertised: false,
  },
  {
    id: 2,
    imageSource: burgerVegan,
    title: "Vegan Burger",
    price: 5.4985,
    quantity: 0,
    isAvailable: true,
    isAdvertised: false,
  },
  {
    id: 3,
    imageSource: burger3,
    title: "Burger poulet",
    price: 5.367,
    quantity: 0,
    isAvailable: true,
    isAdvertised: false,
  },
  {
    id: 4,
    imageSource: drink1,
    title: "Coke 25cl",
    price: 3.568,
    quantity: 0,
    isAvailable: true,
    isAdvertised: false,
  },
  {
    id: 5,
    imageSource: drink2,
    title: "Pepsi 25cl",
    price: 3.487,
    quantity: 0,
    isAvailable: true,
    isAdvertised: false,
  },
  {
    id: 6,
    imageSource: drink3,
    title: "Iced Tea 25cl",
    price: 3.356,
    quantity: 0,
    isAvailable: true,
    isAdvertised: false,
  },
  {
    id: 7,
    imageSource: frite1,
    title: "Frites Paprika",
    price: 2.567,
    quantity: 0,
    isAvailable: true,
    isAdvertised: false,
  },
  {
    id: 8,
    imageSource: frite3,
    title: "New York Fries",
    price: 3.1678,
    quantity: 0,
    isAvailable: true,
    isAdvertised: false,
  },
  {
    id: 9,
    imageSource: wedges1,
    title: "Crispy Potatoes",
    price: 3.7,
    quantity: 0,
    isAvailable: true,
    isAdvertised: false,
  },
  {
    id: 10,
    imageSource: iceCream,
    title: "Glaces artisanales",
    price: 4.678,
    quantity: 0,
    isAvailable: true,
    isAdvertised: false,
  },
]
